package model.am.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jun 22 15:22:12 CEST 2016
// ---------------------------------------------------------------------
public interface CommonAppModule extends ApplicationModule {
    void checkAMConn();
}
