package model.view;

import java.sql.Date;

import java.text.ParseException;
import java.text.SimpleDateFormat;


import model.view.common.ApInvoiceSearchVVO;

import oracle.jbo.ViewCriteria;
import oracle.jbo.ViewCriteriaManager;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jul 18 21:02:07 CEST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ApInvoiceSearchVVOImpl extends ViewObjectImpl implements ApInvoiceSearchVVO {
    /**
     * This is the default constructor (do not remove).
     */


    private static final String SEARCHVIEWCRITERIA =
        "ApInvoiceSearchVVOCriteria";

    public ApInvoiceSearchVVOImpl() {
    }

    /**
     * Returns the variable value for p_VendorName.
     * @return variable value for p_VendorName
     */
    public String getp_VendorName() {
        return (String)ensureVariableManager().getVariableValue("p_VendorName");
    }

    /**
     * Sets <code>value</code> for variable p_VendorName.
     * @param value value to bind as p_VendorName
     */
    public void setp_VendorName(String value) {
        ensureVariableManager().setVariableValue("p_VendorName", value);
    }

    /**
     * Returns the variable value for p_VendorNumber.
     * @return variable value for p_VendorNumber
     */
    public Integer getp_VendorNumber() {
        return (Integer)ensureVariableManager().getVariableValue("p_VendorNumber");
    }

    /**
     * Sets <code>value</code> for variable p_VendorNumber.
     * @param value value to bind as p_VendorNumber
     */
    public void setp_VendorNumber(Integer value) {
        ensureVariableManager().setVariableValue("p_VendorNumber", value);
    }

    /**
     * Returns the variable value for p_MaturityStartDate.
     * @return variable value for p_MaturityStartDate
     */
    public Date getp_MaturityStartDate() {
        return (Date)ensureVariableManager().getVariableValue("p_MaturityStartDate");
    }

    /**
     * Sets <code>value</code> for variable p_MaturityStartDate.
     * @param value value to bind as p_MaturityStartDate
     */
    public void setp_MaturityStartDate(Date value) {
        ensureVariableManager().setVariableValue("p_MaturityStartDate", value);
    }

    /**
     * Returns the variable value for p_MaturityEndDate.
     * @return variable value for p_MaturityEndDate
     */
    public Date getp_MaturityEndDate() {
        return (Date)ensureVariableManager().getVariableValue("p_MaturityEndDate");
    }

    /**
     * Sets <code>value</code> for variable p_MaturityEndDate.
     * @param value value to bind as p_MaturityEndDate
     */
    public void setp_MaturityEndDate(Date value) {
        ensureVariableManager().setVariableValue("p_MaturityEndDate", value);
    }

    /**
     * Returns the variable value for p_InvoiceEndDate.
     * @return variable value for p_InvoiceEndDate
     */
    public Date getp_InvoiceEndDate() {
        return (Date)ensureVariableManager().getVariableValue("p_InvoiceEndDate");
    }

    /**
     * Sets <code>value</code> for variable p_InvoiceEndDate.
     * @param value value to bind as p_InvoiceEndDate
     */
    public void setp_InvoiceEndDate(Date value) {
        ensureVariableManager().setVariableValue("p_InvoiceEndDate", value);
    }

    /**
     * Returns the variable value for p_InvoiceStartDate.
     * @return variable value for p_InvoiceStartDate
     */
    public Date getp_InvoiceStartDate() {
        return (Date)ensureVariableManager().getVariableValue("p_InvoiceStartDate");
    }

    /**
     * Sets <code>value</code> for variable p_InvoiceStartDate.
     * @param value value to bind as p_InvoiceStartDate
     */
    public void setp_InvoiceStartDate(Date value) {
        ensureVariableManager().setVariableValue("p_InvoiceStartDate", value);
    }

    /**
     * Returns the variable value for p_InvoiceNumber.
     * @return variable value for p_InvoiceNumber
     */
    public Long getp_InvoiceNumber() {
        return (Long)ensureVariableManager().getVariableValue("p_InvoiceNumber");
    }

    /**
     * Sets <code>value</code> for variable p_InvoiceNumber.
     * @param value value to bind as p_InvoiceNumber
     */
    public void setp_InvoiceNumber(Long value) {
        ensureVariableManager().setVariableValue("p_InvoiceNumber", value);
    }

    /**
     * Returns the variable value for p_InvoiceCurrencyCode.
     * @return variable value for p_InvoiceCurrencyCode
     */
    public String getp_InvoiceCurrencyCode() {
        return (String)ensureVariableManager().getVariableValue("p_InvoiceCurrencyCode");
    }

    /**
     * Sets <code>value</code> for variable p_InvoiceCurrencyCode.
     * @param value value to bind as p_InvoiceCurrencyCode
     */
    public void setp_InvoiceCurrencyCode(String value) {
        ensureVariableManager().setVariableValue("p_InvoiceCurrencyCode",
                                                 value);
    }

    /**
     * Returns the variable value for p_InvoiceType.
     * @return variable value for p_InvoiceType
     */
    public String getp_InvoiceType() {
        return (String)ensureVariableManager().getVariableValue("p_InvoiceType");
    }

    /**
     * Sets <code>value</code> for variable p_InvoiceType.
     * @param value value to bind as p_InvoiceType
     */
    public void setp_InvoiceType(String value) {
        ensureVariableManager().setVariableValue("p_InvoiceType", value);
    }

    /**
     * Returns the variable value for p_InvoiceToAmount.
     * @return variable value for p_InvoiceToAmount
     */
    public Long getp_InvoiceToAmount() {
        return (Long)ensureVariableManager().getVariableValue("p_InvoiceToAmount");
    }

    /**
     * Sets <code>value</code> for variable p_InvoiceToAmount.
     * @param value value to bind as p_InvoiceToAmount
     */
    public void setp_InvoiceToAmount(Long value) {
        ensureVariableManager().setVariableValue("p_InvoiceToAmount", value);
    }

    /**
     * Returns the variable value for p_InvoiceFromAmount.
     * @return variable value for p_InvoiceFromAmount
     */
    public Long getp_InvoiceFromAmount() {
        return (Long)ensureVariableManager().getVariableValue("p_InvoiceFromAmount");
    }

    /**
     * Sets <code>value</code> for variable p_InvoiceFromAmount.
     * @param value value to bind as p_InvoiceFromAmount
     */
    public void setp_InvoiceFromAmount(Long value) {
        ensureVariableManager().setVariableValue("p_InvoiceFromAmount", value);
    }


    /**
     * @param vendorName
     * @param vendorNumber
     * @param currencyCode
     * @param maturityStartDate
     * @param maturityEndDate
     * @param invoiceStartDate
     * @param invoiceEndDate
     * @param invoiceNumber
     * @param invoiceType
     * @param invoiceFromAmount
     * @param invoiceToAmount
     */
    public void searchInvoice(String vendorName, Integer vendorNumber,
                              String currencyCode, String maturityStartDate,
                              String maturityEndDate, String invoiceStartDate,
                              String invoiceEndDate, Long invoiceNumber,
                              String invoiceType, Long invoiceFromAmount,
                              Long invoiceToAmount, String invoiceStatus) {
        // Remove Applied View Criteria if Any
        ViewCriteriaManager vcm = this.getViewCriteriaManager();
        vcm.removeApplyViewCriteriaName(SEARCHVIEWCRITERIA);

        //  Apply View Criteria
        ViewCriteria vc = this.getViewCriteria(SEARCHVIEWCRITERIA);
        this.applyViewCriteria(vc);
        if (vendorName != null && !vendorName.isEmpty()) {
            setp_VendorName(vendorName);
        } else {
            setp_VendorName(null);
        }
        if (vendorNumber != null) {
            setp_VendorNumber(vendorNumber);
        } else {
            setp_VendorNumber(null);
        }
        if (invoiceNumber != null) {
            setp_InvoiceNumber(invoiceNumber);
        } else {
            setp_InvoiceNumber(null);
        }
        if (currencyCode != null && !currencyCode.isEmpty()) {
            setp_InvoiceCurrencyCode(currencyCode);
        } else {
            setp_InvoiceCurrencyCode(null);
        }
        if (invoiceType != null && !invoiceType.isEmpty()) {
            setp_InvoiceType(invoiceType);
        } else {
            setp_InvoiceType(null);
        }

        if (invoiceStatus != null && !invoiceStatus.isEmpty()) {
            setp_InvoiceStatus(invoiceStatus);
        } else {
            setp_InvoiceStatus(null);
        }

        if (maturityStartDate != null && !maturityStartDate.isEmpty() &&
            maturityEndDate != null && !maturityEndDate.isEmpty()) {

            SimpleDateFormat simpleDateFormat =
                new SimpleDateFormat("dd-MM-yy");
            java.util.Date startDate = null;
            java.util.Date endDate = null;
            try {
                startDate = simpleDateFormat.parse(maturityStartDate);
                endDate = simpleDateFormat.parse(maturityEndDate);
            } catch (ParseException e) {
                e.printStackTrace();
            }
            java.sql.Date sqlStartDate =
                new java.sql.Date(startDate.getTime());
            java.sql.Date sqlEndDate = new java.sql.Date(endDate.getTime());
            setp_MaturityEndDate(sqlEndDate);
            setp_MaturityStartDate(sqlStartDate);

        }

        if (invoiceStartDate != null && !invoiceStartDate.isEmpty() &&
            invoiceEndDate != null && !invoiceEndDate.isEmpty()) {
            SimpleDateFormat simpleDateFormat =
                new SimpleDateFormat("dd-MM-yy");
            java.util.Date startDate = null;
            java.util.Date endDate = null;
            try {
                startDate = simpleDateFormat.parse(invoiceStartDate);
                endDate = simpleDateFormat.parse(invoiceEndDate);
            } catch (ParseException e) {
                e.printStackTrace();
            }
            java.sql.Date sqlStartDate =
                new java.sql.Date(startDate.getTime());
            java.sql.Date sqlEndDate = new java.sql.Date(endDate.getTime());
            setp_InvoiceEndDate(sqlEndDate);
            setp_InvoiceStartDate(sqlStartDate);
        }

        if (invoiceFromAmount != null && invoiceToAmount != null) {
            setp_InvoiceFromAmount(invoiceFromAmount);
            setp_InvoiceToAmount(invoiceToAmount);
        }
        System.out.println(this.getQuery());
        this.executeQuery();
    }

    /**
     * Returns the variable value for p_InvoiceStatus.
     * @return variable value for p_InvoiceStatus
     */
    public String getp_InvoiceStatus() {
        return (String)ensureVariableManager().getVariableValue("p_InvoiceStatus");
    }

    /**
     * Sets <code>value</code> for variable p_InvoiceStatus.
     * @param value value to bind as p_InvoiceStatus
     */
    public void setp_InvoiceStatus(String value) {
        ensureVariableManager().setVariableValue("p_InvoiceStatus", value);
    }
}
