package model.view;

import java.math.BigDecimal;

import java.sql.Date;

import oracle.jbo.RowSet;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jul 18 21:02:07 CEST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ApInvoiceSearchVVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        RowId1,
        GlobalAttribute4,
        GlobalAttributeCategory,
        AwtGroupId,
        CreatedBy,
        CreationDate,
        Description,
        DocCategoryCode,
        ExchangeDate,
        ExchangeRate,
        ExchangeRateType,
        UserRateType,
        GoodsReceivedDate,
        InvoiceAmount,
        InvoiceCurrencyCode,
        InvoiceDate,
        InvoiceId,
        InvoiceNum,
        InvoiceReceivedDate,
        InvoiceTypeLookupCode,
        LastUpdatedBy,
        LastUpdateDate,
        LastUpdateLogin,
        PayGroupLookupCode,
        PoNumber,
        Segment1,
        Source,
        GroupId,
        TermsId,
        VendorId,
        VendorSiteId,
        VoucherNum,
        Status,
        RequestId,
        WorkflowFlag,
        GlDate,
        AcctsPayCodeCombinationId,
        ExclusivePaymentFlag,
        InvoiceType,
        StatusDsp,
        SourceDsp,
        TermsName,
        DocCategoryName,
        VendorName,
        VendorNumber,
        VendorSiteCode,
        InvoiceAmountLimit,
        AwtGroupName,
        OrgId,
        PaymentCrossRateType,
        PaymentCrossRate,
        PaymentCrossRateDate,
        PaymentCurrencyCode,
        AmountApplicableToDiscount,
        PrepayNum,
        PrepayApplyAmount,
        PrepayGlDate,
        InvoiceIncludesPrepayFlag,
        NoXrateBaseAmount,
        TermsDate,
        RequesterId,
        OperatingUnit,
        PrepayLineNum,
        RequesterFirstName,
        RequesterLastName,
        RequesterEmployeeNum,
        LegalEntityId,
        CalcTaxDuringImportFlag,
        ControlAmount,
        AddTaxToInvAmtFlag,
        TaxRelatedInvoiceId,
        TaxationCountry,
        DocumentSubType,
        SupplierTaxInvoiceNumber,
        SupplierTaxInvoiceDate,
        SupplierTaxExchangeRate,
        TaxInvoiceRecordingDate,
        TaxInvoiceInternalSeq,
        PaymentMethodCode,
        IbyPaymentMethod,
        PaymentReasonCode,
        PaymentReason,
        PaymentReasonComments,
        UniqueRemittanceIdentifier,
        UriCheckDigit,
        RemittanceMessage1,
        RemittanceMessage2,
        RemittanceMessage3,
        BankChargeBearer,
        BankChargeBearerDsp,
        DeliveryChannelCode,
        DeliveryChannel,
        SettlementPriority,
        SettlementPriorityDsp,
        PartyId,
        PartySiteId,
        NetOfRetainageFlag,
        PortOfEntryCode,
        ExternalBankAccountId,
        BankAccountName,
        BankAccountNumber,
        PayAwtGroupId,
        PayAwtGroupName,
        RemitToSupplierName,
        RemitToSupplierId,
        RemitToSupplierSite,
        RemitToSupplierSiteId,
        RelationshipId,
        RemitToSupplierNum,
        SupplierNameLOV,
        SupplierNumberLOV,
        InvoiceStatusLOV;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int ROWID1 = AttributesEnum.RowId1.index();
    public static final int GLOBALATTRIBUTE4 = AttributesEnum.GlobalAttribute4.index();
    public static final int GLOBALATTRIBUTECATEGORY = AttributesEnum.GlobalAttributeCategory.index();
    public static final int AWTGROUPID = AttributesEnum.AwtGroupId.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int DESCRIPTION = AttributesEnum.Description.index();
    public static final int DOCCATEGORYCODE = AttributesEnum.DocCategoryCode.index();
    public static final int EXCHANGEDATE = AttributesEnum.ExchangeDate.index();
    public static final int EXCHANGERATE = AttributesEnum.ExchangeRate.index();
    public static final int EXCHANGERATETYPE = AttributesEnum.ExchangeRateType.index();
    public static final int USERRATETYPE = AttributesEnum.UserRateType.index();
    public static final int GOODSRECEIVEDDATE = AttributesEnum.GoodsReceivedDate.index();
    public static final int INVOICEAMOUNT = AttributesEnum.InvoiceAmount.index();
    public static final int INVOICECURRENCYCODE = AttributesEnum.InvoiceCurrencyCode.index();
    public static final int INVOICEDATE = AttributesEnum.InvoiceDate.index();
    public static final int INVOICEID = AttributesEnum.InvoiceId.index();
    public static final int INVOICENUM = AttributesEnum.InvoiceNum.index();
    public static final int INVOICERECEIVEDDATE = AttributesEnum.InvoiceReceivedDate.index();
    public static final int INVOICETYPELOOKUPCODE = AttributesEnum.InvoiceTypeLookupCode.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATELOGIN = AttributesEnum.LastUpdateLogin.index();
    public static final int PAYGROUPLOOKUPCODE = AttributesEnum.PayGroupLookupCode.index();
    public static final int PONUMBER = AttributesEnum.PoNumber.index();
    public static final int SEGMENT1 = AttributesEnum.Segment1.index();
    public static final int SOURCE = AttributesEnum.Source.index();
    public static final int GROUPID = AttributesEnum.GroupId.index();
    public static final int TERMSID = AttributesEnum.TermsId.index();
    public static final int VENDORID = AttributesEnum.VendorId.index();
    public static final int VENDORSITEID = AttributesEnum.VendorSiteId.index();
    public static final int VOUCHERNUM = AttributesEnum.VoucherNum.index();
    public static final int STATUS = AttributesEnum.Status.index();
    public static final int REQUESTID = AttributesEnum.RequestId.index();
    public static final int WORKFLOWFLAG = AttributesEnum.WorkflowFlag.index();
    public static final int GLDATE = AttributesEnum.GlDate.index();
    public static final int ACCTSPAYCODECOMBINATIONID = AttributesEnum.AcctsPayCodeCombinationId.index();
    public static final int EXCLUSIVEPAYMENTFLAG = AttributesEnum.ExclusivePaymentFlag.index();
    public static final int INVOICETYPE = AttributesEnum.InvoiceType.index();
    public static final int STATUSDSP = AttributesEnum.StatusDsp.index();
    public static final int SOURCEDSP = AttributesEnum.SourceDsp.index();
    public static final int TERMSNAME = AttributesEnum.TermsName.index();
    public static final int DOCCATEGORYNAME = AttributesEnum.DocCategoryName.index();
    public static final int VENDORNAME = AttributesEnum.VendorName.index();
    public static final int VENDORNUMBER = AttributesEnum.VendorNumber.index();
    public static final int VENDORSITECODE = AttributesEnum.VendorSiteCode.index();
    public static final int INVOICEAMOUNTLIMIT = AttributesEnum.InvoiceAmountLimit.index();
    public static final int AWTGROUPNAME = AttributesEnum.AwtGroupName.index();
    public static final int ORGID = AttributesEnum.OrgId.index();
    public static final int PAYMENTCROSSRATETYPE = AttributesEnum.PaymentCrossRateType.index();
    public static final int PAYMENTCROSSRATE = AttributesEnum.PaymentCrossRate.index();
    public static final int PAYMENTCROSSRATEDATE = AttributesEnum.PaymentCrossRateDate.index();
    public static final int PAYMENTCURRENCYCODE = AttributesEnum.PaymentCurrencyCode.index();
    public static final int AMOUNTAPPLICABLETODISCOUNT = AttributesEnum.AmountApplicableToDiscount.index();
    public static final int PREPAYNUM = AttributesEnum.PrepayNum.index();
    public static final int PREPAYAPPLYAMOUNT = AttributesEnum.PrepayApplyAmount.index();
    public static final int PREPAYGLDATE = AttributesEnum.PrepayGlDate.index();
    public static final int INVOICEINCLUDESPREPAYFLAG = AttributesEnum.InvoiceIncludesPrepayFlag.index();
    public static final int NOXRATEBASEAMOUNT = AttributesEnum.NoXrateBaseAmount.index();
    public static final int TERMSDATE = AttributesEnum.TermsDate.index();
    public static final int REQUESTERID = AttributesEnum.RequesterId.index();
    public static final int OPERATINGUNIT = AttributesEnum.OperatingUnit.index();
    public static final int PREPAYLINENUM = AttributesEnum.PrepayLineNum.index();
    public static final int REQUESTERFIRSTNAME = AttributesEnum.RequesterFirstName.index();
    public static final int REQUESTERLASTNAME = AttributesEnum.RequesterLastName.index();
    public static final int REQUESTEREMPLOYEENUM = AttributesEnum.RequesterEmployeeNum.index();
    public static final int LEGALENTITYID = AttributesEnum.LegalEntityId.index();
    public static final int CALCTAXDURINGIMPORTFLAG = AttributesEnum.CalcTaxDuringImportFlag.index();
    public static final int CONTROLAMOUNT = AttributesEnum.ControlAmount.index();
    public static final int ADDTAXTOINVAMTFLAG = AttributesEnum.AddTaxToInvAmtFlag.index();
    public static final int TAXRELATEDINVOICEID = AttributesEnum.TaxRelatedInvoiceId.index();
    public static final int TAXATIONCOUNTRY = AttributesEnum.TaxationCountry.index();
    public static final int DOCUMENTSUBTYPE = AttributesEnum.DocumentSubType.index();
    public static final int SUPPLIERTAXINVOICENUMBER = AttributesEnum.SupplierTaxInvoiceNumber.index();
    public static final int SUPPLIERTAXINVOICEDATE = AttributesEnum.SupplierTaxInvoiceDate.index();
    public static final int SUPPLIERTAXEXCHANGERATE = AttributesEnum.SupplierTaxExchangeRate.index();
    public static final int TAXINVOICERECORDINGDATE = AttributesEnum.TaxInvoiceRecordingDate.index();
    public static final int TAXINVOICEINTERNALSEQ = AttributesEnum.TaxInvoiceInternalSeq.index();
    public static final int PAYMENTMETHODCODE = AttributesEnum.PaymentMethodCode.index();
    public static final int IBYPAYMENTMETHOD = AttributesEnum.IbyPaymentMethod.index();
    public static final int PAYMENTREASONCODE = AttributesEnum.PaymentReasonCode.index();
    public static final int PAYMENTREASON = AttributesEnum.PaymentReason.index();
    public static final int PAYMENTREASONCOMMENTS = AttributesEnum.PaymentReasonComments.index();
    public static final int UNIQUEREMITTANCEIDENTIFIER = AttributesEnum.UniqueRemittanceIdentifier.index();
    public static final int URICHECKDIGIT = AttributesEnum.UriCheckDigit.index();
    public static final int REMITTANCEMESSAGE1 = AttributesEnum.RemittanceMessage1.index();
    public static final int REMITTANCEMESSAGE2 = AttributesEnum.RemittanceMessage2.index();
    public static final int REMITTANCEMESSAGE3 = AttributesEnum.RemittanceMessage3.index();
    public static final int BANKCHARGEBEARER = AttributesEnum.BankChargeBearer.index();
    public static final int BANKCHARGEBEARERDSP = AttributesEnum.BankChargeBearerDsp.index();
    public static final int DELIVERYCHANNELCODE = AttributesEnum.DeliveryChannelCode.index();
    public static final int DELIVERYCHANNEL = AttributesEnum.DeliveryChannel.index();
    public static final int SETTLEMENTPRIORITY = AttributesEnum.SettlementPriority.index();
    public static final int SETTLEMENTPRIORITYDSP = AttributesEnum.SettlementPriorityDsp.index();
    public static final int PARTYID = AttributesEnum.PartyId.index();
    public static final int PARTYSITEID = AttributesEnum.PartySiteId.index();
    public static final int NETOFRETAINAGEFLAG = AttributesEnum.NetOfRetainageFlag.index();
    public static final int PORTOFENTRYCODE = AttributesEnum.PortOfEntryCode.index();
    public static final int EXTERNALBANKACCOUNTID = AttributesEnum.ExternalBankAccountId.index();
    public static final int BANKACCOUNTNAME = AttributesEnum.BankAccountName.index();
    public static final int BANKACCOUNTNUMBER = AttributesEnum.BankAccountNumber.index();
    public static final int PAYAWTGROUPID = AttributesEnum.PayAwtGroupId.index();
    public static final int PAYAWTGROUPNAME = AttributesEnum.PayAwtGroupName.index();
    public static final int REMITTOSUPPLIERNAME = AttributesEnum.RemitToSupplierName.index();
    public static final int REMITTOSUPPLIERID = AttributesEnum.RemitToSupplierId.index();
    public static final int REMITTOSUPPLIERSITE = AttributesEnum.RemitToSupplierSite.index();
    public static final int REMITTOSUPPLIERSITEID = AttributesEnum.RemitToSupplierSiteId.index();
    public static final int RELATIONSHIPID = AttributesEnum.RelationshipId.index();
    public static final int REMITTOSUPPLIERNUM = AttributesEnum.RemitToSupplierNum.index();
    public static final int SUPPLIERNAMELOV = AttributesEnum.SupplierNameLOV.index();
    public static final int SUPPLIERNUMBERLOV = AttributesEnum.SupplierNumberLOV.index();
    public static final int INVOICESTATUSLOV = AttributesEnum.InvoiceStatusLOV.index();

    /**
     * This is the default constructor (do not remove).
     */
    public ApInvoiceSearchVVORowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute RowId1.
     * @return the RowId1
     */
    public String getRowId1() {
        return (String) getAttributeInternal(ROWID1);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute RowId1.
     * @param value value to set the  RowId1
     */
    public void setRowId1(String value) {
        setAttributeInternal(ROWID1, value);
    }

    /**
     * Gets the attribute value for the calculated attribute GlobalAttribute4.
     * @return the GlobalAttribute4
     */
    public String getGlobalAttribute4() {
        return (String) getAttributeInternal(GLOBALATTRIBUTE4);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute GlobalAttribute4.
     * @param value value to set the  GlobalAttribute4
     */
    public void setGlobalAttribute4(String value) {
        setAttributeInternal(GLOBALATTRIBUTE4, value);
    }

    /**
     * Gets the attribute value for the calculated attribute GlobalAttributeCategory.
     * @return the GlobalAttributeCategory
     */
    public String getGlobalAttributeCategory() {
        return (String) getAttributeInternal(GLOBALATTRIBUTECATEGORY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute GlobalAttributeCategory.
     * @param value value to set the  GlobalAttributeCategory
     */
    public void setGlobalAttributeCategory(String value) {
        setAttributeInternal(GLOBALATTRIBUTECATEGORY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute AwtGroupId.
     * @return the AwtGroupId
     */
    public BigDecimal getAwtGroupId() {
        return (BigDecimal) getAttributeInternal(AWTGROUPID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute AwtGroupId.
     * @param value value to set the  AwtGroupId
     */
    public void setAwtGroupId(BigDecimal value) {
        setAttributeInternal(AWTGROUPID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CreatedBy.
     * @return the CreatedBy
     */
    public BigDecimal getCreatedBy() {
        return (BigDecimal) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CreatedBy.
     * @param value value to set the  CreatedBy
     */
    public void setCreatedBy(BigDecimal value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CreationDate.
     * @return the CreationDate
     */
    public Date getCreationDate() {
        return (Date) getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CreationDate.
     * @param value value to set the  CreationDate
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Description.
     * @return the Description
     */
    public String getDescription() {
        return (String) getAttributeInternal(DESCRIPTION);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Description.
     * @param value value to set the  Description
     */
    public void setDescription(String value) {
        setAttributeInternal(DESCRIPTION, value);
    }

    /**
     * Gets the attribute value for the calculated attribute DocCategoryCode.
     * @return the DocCategoryCode
     */
    public String getDocCategoryCode() {
        return (String) getAttributeInternal(DOCCATEGORYCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute DocCategoryCode.
     * @param value value to set the  DocCategoryCode
     */
    public void setDocCategoryCode(String value) {
        setAttributeInternal(DOCCATEGORYCODE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ExchangeDate.
     * @return the ExchangeDate
     */
    public Date getExchangeDate() {
        return (Date) getAttributeInternal(EXCHANGEDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ExchangeDate.
     * @param value value to set the  ExchangeDate
     */
    public void setExchangeDate(Date value) {
        setAttributeInternal(EXCHANGEDATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ExchangeRate.
     * @return the ExchangeRate
     */
    public BigDecimal getExchangeRate() {
        return (BigDecimal) getAttributeInternal(EXCHANGERATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ExchangeRate.
     * @param value value to set the  ExchangeRate
     */
    public void setExchangeRate(BigDecimal value) {
        setAttributeInternal(EXCHANGERATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ExchangeRateType.
     * @return the ExchangeRateType
     */
    public String getExchangeRateType() {
        return (String) getAttributeInternal(EXCHANGERATETYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ExchangeRateType.
     * @param value value to set the  ExchangeRateType
     */
    public void setExchangeRateType(String value) {
        setAttributeInternal(EXCHANGERATETYPE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute UserRateType.
     * @return the UserRateType
     */
    public String getUserRateType() {
        return (String) getAttributeInternal(USERRATETYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute UserRateType.
     * @param value value to set the  UserRateType
     */
    public void setUserRateType(String value) {
        setAttributeInternal(USERRATETYPE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute GoodsReceivedDate.
     * @return the GoodsReceivedDate
     */
    public Date getGoodsReceivedDate() {
        return (Date) getAttributeInternal(GOODSRECEIVEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute GoodsReceivedDate.
     * @param value value to set the  GoodsReceivedDate
     */
    public void setGoodsReceivedDate(Date value) {
        setAttributeInternal(GOODSRECEIVEDDATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute InvoiceAmount.
     * @return the InvoiceAmount
     */
    public BigDecimal getInvoiceAmount() {
        return (BigDecimal) getAttributeInternal(INVOICEAMOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute InvoiceAmount.
     * @param value value to set the  InvoiceAmount
     */
    public void setInvoiceAmount(BigDecimal value) {
        setAttributeInternal(INVOICEAMOUNT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute InvoiceCurrencyCode.
     * @return the InvoiceCurrencyCode
     */
    public String getInvoiceCurrencyCode() {
        return (String) getAttributeInternal(INVOICECURRENCYCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute InvoiceCurrencyCode.
     * @param value value to set the  InvoiceCurrencyCode
     */
    public void setInvoiceCurrencyCode(String value) {
        setAttributeInternal(INVOICECURRENCYCODE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute InvoiceDate.
     * @return the InvoiceDate
     */
    public Date getInvoiceDate() {
        return (Date) getAttributeInternal(INVOICEDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute InvoiceDate.
     * @param value value to set the  InvoiceDate
     */
    public void setInvoiceDate(Date value) {
        setAttributeInternal(INVOICEDATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute InvoiceId.
     * @return the InvoiceId
     */
    public BigDecimal getInvoiceId() {
        return (BigDecimal) getAttributeInternal(INVOICEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute InvoiceId.
     * @param value value to set the  InvoiceId
     */
    public void setInvoiceId(BigDecimal value) {
        setAttributeInternal(INVOICEID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute InvoiceNum.
     * @return the InvoiceNum
     */
    public String getInvoiceNum() {
        return (String) getAttributeInternal(INVOICENUM);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute InvoiceNum.
     * @param value value to set the  InvoiceNum
     */
    public void setInvoiceNum(String value) {
        setAttributeInternal(INVOICENUM, value);
    }

    /**
     * Gets the attribute value for the calculated attribute InvoiceReceivedDate.
     * @return the InvoiceReceivedDate
     */
    public Date getInvoiceReceivedDate() {
        return (Date) getAttributeInternal(INVOICERECEIVEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute InvoiceReceivedDate.
     * @param value value to set the  InvoiceReceivedDate
     */
    public void setInvoiceReceivedDate(Date value) {
        setAttributeInternal(INVOICERECEIVEDDATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute InvoiceTypeLookupCode.
     * @return the InvoiceTypeLookupCode
     */
    public String getInvoiceTypeLookupCode() {
        return (String) getAttributeInternal(INVOICETYPELOOKUPCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute InvoiceTypeLookupCode.
     * @param value value to set the  InvoiceTypeLookupCode
     */
    public void setInvoiceTypeLookupCode(String value) {
        setAttributeInternal(INVOICETYPELOOKUPCODE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute LastUpdatedBy.
     * @return the LastUpdatedBy
     */
    public BigDecimal getLastUpdatedBy() {
        return (BigDecimal) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute LastUpdatedBy.
     * @param value value to set the  LastUpdatedBy
     */
    public void setLastUpdatedBy(BigDecimal value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute LastUpdateDate.
     * @return the LastUpdateDate
     */
    public Date getLastUpdateDate() {
        return (Date) getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute LastUpdateDate.
     * @param value value to set the  LastUpdateDate
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute LastUpdateLogin.
     * @return the LastUpdateLogin
     */
    public BigDecimal getLastUpdateLogin() {
        return (BigDecimal) getAttributeInternal(LASTUPDATELOGIN);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute LastUpdateLogin.
     * @param value value to set the  LastUpdateLogin
     */
    public void setLastUpdateLogin(BigDecimal value) {
        setAttributeInternal(LASTUPDATELOGIN, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PayGroupLookupCode.
     * @return the PayGroupLookupCode
     */
    public String getPayGroupLookupCode() {
        return (String) getAttributeInternal(PAYGROUPLOOKUPCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PayGroupLookupCode.
     * @param value value to set the  PayGroupLookupCode
     */
    public void setPayGroupLookupCode(String value) {
        setAttributeInternal(PAYGROUPLOOKUPCODE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PoNumber.
     * @return the PoNumber
     */
    public String getPoNumber() {
        return (String) getAttributeInternal(PONUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PoNumber.
     * @param value value to set the  PoNumber
     */
    public void setPoNumber(String value) {
        setAttributeInternal(PONUMBER, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Segment1.
     * @return the Segment1
     */
    public String getSegment1() {
        return (String) getAttributeInternal(SEGMENT1);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Segment1.
     * @param value value to set the  Segment1
     */
    public void setSegment1(String value) {
        setAttributeInternal(SEGMENT1, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Source.
     * @return the Source
     */
    public String getSource() {
        return (String) getAttributeInternal(SOURCE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Source.
     * @param value value to set the  Source
     */
    public void setSource(String value) {
        setAttributeInternal(SOURCE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute GroupId.
     * @return the GroupId
     */
    public String getGroupId() {
        return (String) getAttributeInternal(GROUPID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute GroupId.
     * @param value value to set the  GroupId
     */
    public void setGroupId(String value) {
        setAttributeInternal(GROUPID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TermsId.
     * @return the TermsId
     */
    public BigDecimal getTermsId() {
        return (BigDecimal) getAttributeInternal(TERMSID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TermsId.
     * @param value value to set the  TermsId
     */
    public void setTermsId(BigDecimal value) {
        setAttributeInternal(TERMSID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute VendorId.
     * @return the VendorId
     */
    public BigDecimal getVendorId() {
        return (BigDecimal) getAttributeInternal(VENDORID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute VendorId.
     * @param value value to set the  VendorId
     */
    public void setVendorId(BigDecimal value) {
        setAttributeInternal(VENDORID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute VendorSiteId.
     * @return the VendorSiteId
     */
    public BigDecimal getVendorSiteId() {
        return (BigDecimal) getAttributeInternal(VENDORSITEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute VendorSiteId.
     * @param value value to set the  VendorSiteId
     */
    public void setVendorSiteId(BigDecimal value) {
        setAttributeInternal(VENDORSITEID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute VoucherNum.
     * @return the VoucherNum
     */
    public String getVoucherNum() {
        return (String) getAttributeInternal(VOUCHERNUM);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute VoucherNum.
     * @param value value to set the  VoucherNum
     */
    public void setVoucherNum(String value) {
        setAttributeInternal(VOUCHERNUM, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Status.
     * @return the Status
     */
    public String getStatus() {
        return (String) getAttributeInternal(STATUS);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Status.
     * @param value value to set the  Status
     */
    public void setStatus(String value) {
        setAttributeInternal(STATUS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute RequestId.
     * @return the RequestId
     */
    public BigDecimal getRequestId() {
        return (BigDecimal) getAttributeInternal(REQUESTID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute RequestId.
     * @param value value to set the  RequestId
     */
    public void setRequestId(BigDecimal value) {
        setAttributeInternal(REQUESTID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute WorkflowFlag.
     * @return the WorkflowFlag
     */
    public String getWorkflowFlag() {
        return (String) getAttributeInternal(WORKFLOWFLAG);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute WorkflowFlag.
     * @param value value to set the  WorkflowFlag
     */
    public void setWorkflowFlag(String value) {
        setAttributeInternal(WORKFLOWFLAG, value);
    }

    /**
     * Gets the attribute value for the calculated attribute GlDate.
     * @return the GlDate
     */
    public Date getGlDate() {
        return (Date) getAttributeInternal(GLDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute GlDate.
     * @param value value to set the  GlDate
     */
    public void setGlDate(Date value) {
        setAttributeInternal(GLDATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute AcctsPayCodeCombinationId.
     * @return the AcctsPayCodeCombinationId
     */
    public BigDecimal getAcctsPayCodeCombinationId() {
        return (BigDecimal) getAttributeInternal(ACCTSPAYCODECOMBINATIONID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute AcctsPayCodeCombinationId.
     * @param value value to set the  AcctsPayCodeCombinationId
     */
    public void setAcctsPayCodeCombinationId(BigDecimal value) {
        setAttributeInternal(ACCTSPAYCODECOMBINATIONID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ExclusivePaymentFlag.
     * @return the ExclusivePaymentFlag
     */
    public String getExclusivePaymentFlag() {
        return (String) getAttributeInternal(EXCLUSIVEPAYMENTFLAG);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ExclusivePaymentFlag.
     * @param value value to set the  ExclusivePaymentFlag
     */
    public void setExclusivePaymentFlag(String value) {
        setAttributeInternal(EXCLUSIVEPAYMENTFLAG, value);
    }

    /**
     * Gets the attribute value for the calculated attribute InvoiceType.
     * @return the InvoiceType
     */
    public String getInvoiceType() {
        return (String) getAttributeInternal(INVOICETYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute InvoiceType.
     * @param value value to set the  InvoiceType
     */
    public void setInvoiceType(String value) {
        setAttributeInternal(INVOICETYPE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute StatusDsp.
     * @return the StatusDsp
     */
    public String getStatusDsp() {
        return (String) getAttributeInternal(STATUSDSP);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute StatusDsp.
     * @param value value to set the  StatusDsp
     */
    public void setStatusDsp(String value) {
        setAttributeInternal(STATUSDSP, value);
    }

    /**
     * Gets the attribute value for the calculated attribute SourceDsp.
     * @return the SourceDsp
     */
    public String getSourceDsp() {
        return (String) getAttributeInternal(SOURCEDSP);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute SourceDsp.
     * @param value value to set the  SourceDsp
     */
    public void setSourceDsp(String value) {
        setAttributeInternal(SOURCEDSP, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TermsName.
     * @return the TermsName
     */
    public String getTermsName() {
        return (String) getAttributeInternal(TERMSNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TermsName.
     * @param value value to set the  TermsName
     */
    public void setTermsName(String value) {
        setAttributeInternal(TERMSNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute DocCategoryName.
     * @return the DocCategoryName
     */
    public String getDocCategoryName() {
        return (String) getAttributeInternal(DOCCATEGORYNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute DocCategoryName.
     * @param value value to set the  DocCategoryName
     */
    public void setDocCategoryName(String value) {
        setAttributeInternal(DOCCATEGORYNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute VendorName.
     * @return the VendorName
     */
    public String getVendorName() {
        return (String) getAttributeInternal(VENDORNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute VendorName.
     * @param value value to set the  VendorName
     */
    public void setVendorName(String value) {
        setAttributeInternal(VENDORNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute VendorNumber.
     * @return the VendorNumber
     */
    public String getVendorNumber() {
        return (String) getAttributeInternal(VENDORNUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute VendorNumber.
     * @param value value to set the  VendorNumber
     */
    public void setVendorNumber(String value) {
        setAttributeInternal(VENDORNUMBER, value);
    }

    /**
     * Gets the attribute value for the calculated attribute VendorSiteCode.
     * @return the VendorSiteCode
     */
    public String getVendorSiteCode() {
        return (String) getAttributeInternal(VENDORSITECODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute VendorSiteCode.
     * @param value value to set the  VendorSiteCode
     */
    public void setVendorSiteCode(String value) {
        setAttributeInternal(VENDORSITECODE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute InvoiceAmountLimit.
     * @return the InvoiceAmountLimit
     */
    public BigDecimal getInvoiceAmountLimit() {
        return (BigDecimal) getAttributeInternal(INVOICEAMOUNTLIMIT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute InvoiceAmountLimit.
     * @param value value to set the  InvoiceAmountLimit
     */
    public void setInvoiceAmountLimit(BigDecimal value) {
        setAttributeInternal(INVOICEAMOUNTLIMIT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute AwtGroupName.
     * @return the AwtGroupName
     */
    public String getAwtGroupName() {
        return (String) getAttributeInternal(AWTGROUPNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute AwtGroupName.
     * @param value value to set the  AwtGroupName
     */
    public void setAwtGroupName(String value) {
        setAttributeInternal(AWTGROUPNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute OrgId.
     * @return the OrgId
     */
    public BigDecimal getOrgId() {
        return (BigDecimal) getAttributeInternal(ORGID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute OrgId.
     * @param value value to set the  OrgId
     */
    public void setOrgId(BigDecimal value) {
        setAttributeInternal(ORGID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PaymentCrossRateType.
     * @return the PaymentCrossRateType
     */
    public String getPaymentCrossRateType() {
        return (String) getAttributeInternal(PAYMENTCROSSRATETYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PaymentCrossRateType.
     * @param value value to set the  PaymentCrossRateType
     */
    public void setPaymentCrossRateType(String value) {
        setAttributeInternal(PAYMENTCROSSRATETYPE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PaymentCrossRate.
     * @return the PaymentCrossRate
     */
    public BigDecimal getPaymentCrossRate() {
        return (BigDecimal) getAttributeInternal(PAYMENTCROSSRATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PaymentCrossRate.
     * @param value value to set the  PaymentCrossRate
     */
    public void setPaymentCrossRate(BigDecimal value) {
        setAttributeInternal(PAYMENTCROSSRATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PaymentCrossRateDate.
     * @return the PaymentCrossRateDate
     */
    public Date getPaymentCrossRateDate() {
        return (Date) getAttributeInternal(PAYMENTCROSSRATEDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PaymentCrossRateDate.
     * @param value value to set the  PaymentCrossRateDate
     */
    public void setPaymentCrossRateDate(Date value) {
        setAttributeInternal(PAYMENTCROSSRATEDATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PaymentCurrencyCode.
     * @return the PaymentCurrencyCode
     */
    public String getPaymentCurrencyCode() {
        return (String) getAttributeInternal(PAYMENTCURRENCYCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PaymentCurrencyCode.
     * @param value value to set the  PaymentCurrencyCode
     */
    public void setPaymentCurrencyCode(String value) {
        setAttributeInternal(PAYMENTCURRENCYCODE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute AmountApplicableToDiscount.
     * @return the AmountApplicableToDiscount
     */
    public BigDecimal getAmountApplicableToDiscount() {
        return (BigDecimal) getAttributeInternal(AMOUNTAPPLICABLETODISCOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute AmountApplicableToDiscount.
     * @param value value to set the  AmountApplicableToDiscount
     */
    public void setAmountApplicableToDiscount(BigDecimal value) {
        setAttributeInternal(AMOUNTAPPLICABLETODISCOUNT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PrepayNum.
     * @return the PrepayNum
     */
    public String getPrepayNum() {
        return (String) getAttributeInternal(PREPAYNUM);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PrepayNum.
     * @param value value to set the  PrepayNum
     */
    public void setPrepayNum(String value) {
        setAttributeInternal(PREPAYNUM, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PrepayApplyAmount.
     * @return the PrepayApplyAmount
     */
    public BigDecimal getPrepayApplyAmount() {
        return (BigDecimal) getAttributeInternal(PREPAYAPPLYAMOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PrepayApplyAmount.
     * @param value value to set the  PrepayApplyAmount
     */
    public void setPrepayApplyAmount(BigDecimal value) {
        setAttributeInternal(PREPAYAPPLYAMOUNT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PrepayGlDate.
     * @return the PrepayGlDate
     */
    public Date getPrepayGlDate() {
        return (Date) getAttributeInternal(PREPAYGLDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PrepayGlDate.
     * @param value value to set the  PrepayGlDate
     */
    public void setPrepayGlDate(Date value) {
        setAttributeInternal(PREPAYGLDATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute InvoiceIncludesPrepayFlag.
     * @return the InvoiceIncludesPrepayFlag
     */
    public String getInvoiceIncludesPrepayFlag() {
        return (String) getAttributeInternal(INVOICEINCLUDESPREPAYFLAG);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute InvoiceIncludesPrepayFlag.
     * @param value value to set the  InvoiceIncludesPrepayFlag
     */
    public void setInvoiceIncludesPrepayFlag(String value) {
        setAttributeInternal(INVOICEINCLUDESPREPAYFLAG, value);
    }

    /**
     * Gets the attribute value for the calculated attribute NoXrateBaseAmount.
     * @return the NoXrateBaseAmount
     */
    public BigDecimal getNoXrateBaseAmount() {
        return (BigDecimal) getAttributeInternal(NOXRATEBASEAMOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute NoXrateBaseAmount.
     * @param value value to set the  NoXrateBaseAmount
     */
    public void setNoXrateBaseAmount(BigDecimal value) {
        setAttributeInternal(NOXRATEBASEAMOUNT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TermsDate.
     * @return the TermsDate
     */
    public Date getTermsDate() {
        return (Date) getAttributeInternal(TERMSDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TermsDate.
     * @param value value to set the  TermsDate
     */
    public void setTermsDate(Date value) {
        setAttributeInternal(TERMSDATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute RequesterId.
     * @return the RequesterId
     */
    public BigDecimal getRequesterId() {
        return (BigDecimal) getAttributeInternal(REQUESTERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute RequesterId.
     * @param value value to set the  RequesterId
     */
    public void setRequesterId(BigDecimal value) {
        setAttributeInternal(REQUESTERID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute OperatingUnit.
     * @return the OperatingUnit
     */
    public String getOperatingUnit() {
        return (String) getAttributeInternal(OPERATINGUNIT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute OperatingUnit.
     * @param value value to set the  OperatingUnit
     */
    public void setOperatingUnit(String value) {
        setAttributeInternal(OPERATINGUNIT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PrepayLineNum.
     * @return the PrepayLineNum
     */
    public BigDecimal getPrepayLineNum() {
        return (BigDecimal) getAttributeInternal(PREPAYLINENUM);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PrepayLineNum.
     * @param value value to set the  PrepayLineNum
     */
    public void setPrepayLineNum(BigDecimal value) {
        setAttributeInternal(PREPAYLINENUM, value);
    }

    /**
     * Gets the attribute value for the calculated attribute RequesterFirstName.
     * @return the RequesterFirstName
     */
    public String getRequesterFirstName() {
        return (String) getAttributeInternal(REQUESTERFIRSTNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute RequesterFirstName.
     * @param value value to set the  RequesterFirstName
     */
    public void setRequesterFirstName(String value) {
        setAttributeInternal(REQUESTERFIRSTNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute RequesterLastName.
     * @return the RequesterLastName
     */
    public String getRequesterLastName() {
        return (String) getAttributeInternal(REQUESTERLASTNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute RequesterLastName.
     * @param value value to set the  RequesterLastName
     */
    public void setRequesterLastName(String value) {
        setAttributeInternal(REQUESTERLASTNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute RequesterEmployeeNum.
     * @return the RequesterEmployeeNum
     */
    public String getRequesterEmployeeNum() {
        return (String) getAttributeInternal(REQUESTEREMPLOYEENUM);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute RequesterEmployeeNum.
     * @param value value to set the  RequesterEmployeeNum
     */
    public void setRequesterEmployeeNum(String value) {
        setAttributeInternal(REQUESTEREMPLOYEENUM, value);
    }

    /**
     * Gets the attribute value for the calculated attribute LegalEntityId.
     * @return the LegalEntityId
     */
    public BigDecimal getLegalEntityId() {
        return (BigDecimal) getAttributeInternal(LEGALENTITYID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute LegalEntityId.
     * @param value value to set the  LegalEntityId
     */
    public void setLegalEntityId(BigDecimal value) {
        setAttributeInternal(LEGALENTITYID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CalcTaxDuringImportFlag.
     * @return the CalcTaxDuringImportFlag
     */
    public String getCalcTaxDuringImportFlag() {
        return (String) getAttributeInternal(CALCTAXDURINGIMPORTFLAG);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CalcTaxDuringImportFlag.
     * @param value value to set the  CalcTaxDuringImportFlag
     */
    public void setCalcTaxDuringImportFlag(String value) {
        setAttributeInternal(CALCTAXDURINGIMPORTFLAG, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ControlAmount.
     * @return the ControlAmount
     */
    public BigDecimal getControlAmount() {
        return (BigDecimal) getAttributeInternal(CONTROLAMOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ControlAmount.
     * @param value value to set the  ControlAmount
     */
    public void setControlAmount(BigDecimal value) {
        setAttributeInternal(CONTROLAMOUNT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute AddTaxToInvAmtFlag.
     * @return the AddTaxToInvAmtFlag
     */
    public String getAddTaxToInvAmtFlag() {
        return (String) getAttributeInternal(ADDTAXTOINVAMTFLAG);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute AddTaxToInvAmtFlag.
     * @param value value to set the  AddTaxToInvAmtFlag
     */
    public void setAddTaxToInvAmtFlag(String value) {
        setAttributeInternal(ADDTAXTOINVAMTFLAG, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TaxRelatedInvoiceId.
     * @return the TaxRelatedInvoiceId
     */
    public BigDecimal getTaxRelatedInvoiceId() {
        return (BigDecimal) getAttributeInternal(TAXRELATEDINVOICEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TaxRelatedInvoiceId.
     * @param value value to set the  TaxRelatedInvoiceId
     */
    public void setTaxRelatedInvoiceId(BigDecimal value) {
        setAttributeInternal(TAXRELATEDINVOICEID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TaxationCountry.
     * @return the TaxationCountry
     */
    public String getTaxationCountry() {
        return (String) getAttributeInternal(TAXATIONCOUNTRY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TaxationCountry.
     * @param value value to set the  TaxationCountry
     */
    public void setTaxationCountry(String value) {
        setAttributeInternal(TAXATIONCOUNTRY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute DocumentSubType.
     * @return the DocumentSubType
     */
    public String getDocumentSubType() {
        return (String) getAttributeInternal(DOCUMENTSUBTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute DocumentSubType.
     * @param value value to set the  DocumentSubType
     */
    public void setDocumentSubType(String value) {
        setAttributeInternal(DOCUMENTSUBTYPE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute SupplierTaxInvoiceNumber.
     * @return the SupplierTaxInvoiceNumber
     */
    public String getSupplierTaxInvoiceNumber() {
        return (String) getAttributeInternal(SUPPLIERTAXINVOICENUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute SupplierTaxInvoiceNumber.
     * @param value value to set the  SupplierTaxInvoiceNumber
     */
    public void setSupplierTaxInvoiceNumber(String value) {
        setAttributeInternal(SUPPLIERTAXINVOICENUMBER, value);
    }

    /**
     * Gets the attribute value for the calculated attribute SupplierTaxInvoiceDate.
     * @return the SupplierTaxInvoiceDate
     */
    public Date getSupplierTaxInvoiceDate() {
        return (Date) getAttributeInternal(SUPPLIERTAXINVOICEDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute SupplierTaxInvoiceDate.
     * @param value value to set the  SupplierTaxInvoiceDate
     */
    public void setSupplierTaxInvoiceDate(Date value) {
        setAttributeInternal(SUPPLIERTAXINVOICEDATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute SupplierTaxExchangeRate.
     * @return the SupplierTaxExchangeRate
     */
    public BigDecimal getSupplierTaxExchangeRate() {
        return (BigDecimal) getAttributeInternal(SUPPLIERTAXEXCHANGERATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute SupplierTaxExchangeRate.
     * @param value value to set the  SupplierTaxExchangeRate
     */
    public void setSupplierTaxExchangeRate(BigDecimal value) {
        setAttributeInternal(SUPPLIERTAXEXCHANGERATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TaxInvoiceRecordingDate.
     * @return the TaxInvoiceRecordingDate
     */
    public Date getTaxInvoiceRecordingDate() {
        return (Date) getAttributeInternal(TAXINVOICERECORDINGDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TaxInvoiceRecordingDate.
     * @param value value to set the  TaxInvoiceRecordingDate
     */
    public void setTaxInvoiceRecordingDate(Date value) {
        setAttributeInternal(TAXINVOICERECORDINGDATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TaxInvoiceInternalSeq.
     * @return the TaxInvoiceInternalSeq
     */
    public String getTaxInvoiceInternalSeq() {
        return (String) getAttributeInternal(TAXINVOICEINTERNALSEQ);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TaxInvoiceInternalSeq.
     * @param value value to set the  TaxInvoiceInternalSeq
     */
    public void setTaxInvoiceInternalSeq(String value) {
        setAttributeInternal(TAXINVOICEINTERNALSEQ, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PaymentMethodCode.
     * @return the PaymentMethodCode
     */
    public String getPaymentMethodCode() {
        return (String) getAttributeInternal(PAYMENTMETHODCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PaymentMethodCode.
     * @param value value to set the  PaymentMethodCode
     */
    public void setPaymentMethodCode(String value) {
        setAttributeInternal(PAYMENTMETHODCODE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute IbyPaymentMethod.
     * @return the IbyPaymentMethod
     */
    public String getIbyPaymentMethod() {
        return (String) getAttributeInternal(IBYPAYMENTMETHOD);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute IbyPaymentMethod.
     * @param value value to set the  IbyPaymentMethod
     */
    public void setIbyPaymentMethod(String value) {
        setAttributeInternal(IBYPAYMENTMETHOD, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PaymentReasonCode.
     * @return the PaymentReasonCode
     */
    public String getPaymentReasonCode() {
        return (String) getAttributeInternal(PAYMENTREASONCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PaymentReasonCode.
     * @param value value to set the  PaymentReasonCode
     */
    public void setPaymentReasonCode(String value) {
        setAttributeInternal(PAYMENTREASONCODE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PaymentReason.
     * @return the PaymentReason
     */
    public String getPaymentReason() {
        return (String) getAttributeInternal(PAYMENTREASON);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PaymentReason.
     * @param value value to set the  PaymentReason
     */
    public void setPaymentReason(String value) {
        setAttributeInternal(PAYMENTREASON, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PaymentReasonComments.
     * @return the PaymentReasonComments
     */
    public String getPaymentReasonComments() {
        return (String) getAttributeInternal(PAYMENTREASONCOMMENTS);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PaymentReasonComments.
     * @param value value to set the  PaymentReasonComments
     */
    public void setPaymentReasonComments(String value) {
        setAttributeInternal(PAYMENTREASONCOMMENTS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute UniqueRemittanceIdentifier.
     * @return the UniqueRemittanceIdentifier
     */
    public String getUniqueRemittanceIdentifier() {
        return (String) getAttributeInternal(UNIQUEREMITTANCEIDENTIFIER);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute UniqueRemittanceIdentifier.
     * @param value value to set the  UniqueRemittanceIdentifier
     */
    public void setUniqueRemittanceIdentifier(String value) {
        setAttributeInternal(UNIQUEREMITTANCEIDENTIFIER, value);
    }

    /**
     * Gets the attribute value for the calculated attribute UriCheckDigit.
     * @return the UriCheckDigit
     */
    public String getUriCheckDigit() {
        return (String) getAttributeInternal(URICHECKDIGIT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute UriCheckDigit.
     * @param value value to set the  UriCheckDigit
     */
    public void setUriCheckDigit(String value) {
        setAttributeInternal(URICHECKDIGIT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute RemittanceMessage1.
     * @return the RemittanceMessage1
     */
    public String getRemittanceMessage1() {
        return (String) getAttributeInternal(REMITTANCEMESSAGE1);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute RemittanceMessage1.
     * @param value value to set the  RemittanceMessage1
     */
    public void setRemittanceMessage1(String value) {
        setAttributeInternal(REMITTANCEMESSAGE1, value);
    }

    /**
     * Gets the attribute value for the calculated attribute RemittanceMessage2.
     * @return the RemittanceMessage2
     */
    public String getRemittanceMessage2() {
        return (String) getAttributeInternal(REMITTANCEMESSAGE2);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute RemittanceMessage2.
     * @param value value to set the  RemittanceMessage2
     */
    public void setRemittanceMessage2(String value) {
        setAttributeInternal(REMITTANCEMESSAGE2, value);
    }

    /**
     * Gets the attribute value for the calculated attribute RemittanceMessage3.
     * @return the RemittanceMessage3
     */
    public String getRemittanceMessage3() {
        return (String) getAttributeInternal(REMITTANCEMESSAGE3);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute RemittanceMessage3.
     * @param value value to set the  RemittanceMessage3
     */
    public void setRemittanceMessage3(String value) {
        setAttributeInternal(REMITTANCEMESSAGE3, value);
    }

    /**
     * Gets the attribute value for the calculated attribute BankChargeBearer.
     * @return the BankChargeBearer
     */
    public String getBankChargeBearer() {
        return (String) getAttributeInternal(BANKCHARGEBEARER);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute BankChargeBearer.
     * @param value value to set the  BankChargeBearer
     */
    public void setBankChargeBearer(String value) {
        setAttributeInternal(BANKCHARGEBEARER, value);
    }

    /**
     * Gets the attribute value for the calculated attribute BankChargeBearerDsp.
     * @return the BankChargeBearerDsp
     */
    public String getBankChargeBearerDsp() {
        return (String) getAttributeInternal(BANKCHARGEBEARERDSP);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute BankChargeBearerDsp.
     * @param value value to set the  BankChargeBearerDsp
     */
    public void setBankChargeBearerDsp(String value) {
        setAttributeInternal(BANKCHARGEBEARERDSP, value);
    }

    /**
     * Gets the attribute value for the calculated attribute DeliveryChannelCode.
     * @return the DeliveryChannelCode
     */
    public String getDeliveryChannelCode() {
        return (String) getAttributeInternal(DELIVERYCHANNELCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute DeliveryChannelCode.
     * @param value value to set the  DeliveryChannelCode
     */
    public void setDeliveryChannelCode(String value) {
        setAttributeInternal(DELIVERYCHANNELCODE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute DeliveryChannel.
     * @return the DeliveryChannel
     */
    public String getDeliveryChannel() {
        return (String) getAttributeInternal(DELIVERYCHANNEL);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute DeliveryChannel.
     * @param value value to set the  DeliveryChannel
     */
    public void setDeliveryChannel(String value) {
        setAttributeInternal(DELIVERYCHANNEL, value);
    }

    /**
     * Gets the attribute value for the calculated attribute SettlementPriority.
     * @return the SettlementPriority
     */
    public String getSettlementPriority() {
        return (String) getAttributeInternal(SETTLEMENTPRIORITY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute SettlementPriority.
     * @param value value to set the  SettlementPriority
     */
    public void setSettlementPriority(String value) {
        setAttributeInternal(SETTLEMENTPRIORITY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute SettlementPriorityDsp.
     * @return the SettlementPriorityDsp
     */
    public String getSettlementPriorityDsp() {
        return (String) getAttributeInternal(SETTLEMENTPRIORITYDSP);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute SettlementPriorityDsp.
     * @param value value to set the  SettlementPriorityDsp
     */
    public void setSettlementPriorityDsp(String value) {
        setAttributeInternal(SETTLEMENTPRIORITYDSP, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PartyId.
     * @return the PartyId
     */
    public BigDecimal getPartyId() {
        return (BigDecimal) getAttributeInternal(PARTYID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PartyId.
     * @param value value to set the  PartyId
     */
    public void setPartyId(BigDecimal value) {
        setAttributeInternal(PARTYID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PartySiteId.
     * @return the PartySiteId
     */
    public BigDecimal getPartySiteId() {
        return (BigDecimal) getAttributeInternal(PARTYSITEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PartySiteId.
     * @param value value to set the  PartySiteId
     */
    public void setPartySiteId(BigDecimal value) {
        setAttributeInternal(PARTYSITEID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute NetOfRetainageFlag.
     * @return the NetOfRetainageFlag
     */
    public String getNetOfRetainageFlag() {
        return (String) getAttributeInternal(NETOFRETAINAGEFLAG);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute NetOfRetainageFlag.
     * @param value value to set the  NetOfRetainageFlag
     */
    public void setNetOfRetainageFlag(String value) {
        setAttributeInternal(NETOFRETAINAGEFLAG, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PortOfEntryCode.
     * @return the PortOfEntryCode
     */
    public String getPortOfEntryCode() {
        return (String) getAttributeInternal(PORTOFENTRYCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PortOfEntryCode.
     * @param value value to set the  PortOfEntryCode
     */
    public void setPortOfEntryCode(String value) {
        setAttributeInternal(PORTOFENTRYCODE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ExternalBankAccountId.
     * @return the ExternalBankAccountId
     */
    public BigDecimal getExternalBankAccountId() {
        return (BigDecimal) getAttributeInternal(EXTERNALBANKACCOUNTID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ExternalBankAccountId.
     * @param value value to set the  ExternalBankAccountId
     */
    public void setExternalBankAccountId(BigDecimal value) {
        setAttributeInternal(EXTERNALBANKACCOUNTID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute BankAccountName.
     * @return the BankAccountName
     */
    public String getBankAccountName() {
        return (String) getAttributeInternal(BANKACCOUNTNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute BankAccountName.
     * @param value value to set the  BankAccountName
     */
    public void setBankAccountName(String value) {
        setAttributeInternal(BANKACCOUNTNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute BankAccountNumber.
     * @return the BankAccountNumber
     */
    public String getBankAccountNumber() {
        return (String) getAttributeInternal(BANKACCOUNTNUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute BankAccountNumber.
     * @param value value to set the  BankAccountNumber
     */
    public void setBankAccountNumber(String value) {
        setAttributeInternal(BANKACCOUNTNUMBER, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PayAwtGroupId.
     * @return the PayAwtGroupId
     */
    public BigDecimal getPayAwtGroupId() {
        return (BigDecimal) getAttributeInternal(PAYAWTGROUPID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PayAwtGroupId.
     * @param value value to set the  PayAwtGroupId
     */
    public void setPayAwtGroupId(BigDecimal value) {
        setAttributeInternal(PAYAWTGROUPID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PayAwtGroupName.
     * @return the PayAwtGroupName
     */
    public String getPayAwtGroupName() {
        return (String) getAttributeInternal(PAYAWTGROUPNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PayAwtGroupName.
     * @param value value to set the  PayAwtGroupName
     */
    public void setPayAwtGroupName(String value) {
        setAttributeInternal(PAYAWTGROUPNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute RemitToSupplierName.
     * @return the RemitToSupplierName
     */
    public String getRemitToSupplierName() {
        return (String) getAttributeInternal(REMITTOSUPPLIERNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute RemitToSupplierName.
     * @param value value to set the  RemitToSupplierName
     */
    public void setRemitToSupplierName(String value) {
        setAttributeInternal(REMITTOSUPPLIERNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute RemitToSupplierId.
     * @return the RemitToSupplierId
     */
    public BigDecimal getRemitToSupplierId() {
        return (BigDecimal) getAttributeInternal(REMITTOSUPPLIERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute RemitToSupplierId.
     * @param value value to set the  RemitToSupplierId
     */
    public void setRemitToSupplierId(BigDecimal value) {
        setAttributeInternal(REMITTOSUPPLIERID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute RemitToSupplierSite.
     * @return the RemitToSupplierSite
     */
    public String getRemitToSupplierSite() {
        return (String) getAttributeInternal(REMITTOSUPPLIERSITE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute RemitToSupplierSite.
     * @param value value to set the  RemitToSupplierSite
     */
    public void setRemitToSupplierSite(String value) {
        setAttributeInternal(REMITTOSUPPLIERSITE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute RemitToSupplierSiteId.
     * @return the RemitToSupplierSiteId
     */
    public BigDecimal getRemitToSupplierSiteId() {
        return (BigDecimal) getAttributeInternal(REMITTOSUPPLIERSITEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute RemitToSupplierSiteId.
     * @param value value to set the  RemitToSupplierSiteId
     */
    public void setRemitToSupplierSiteId(BigDecimal value) {
        setAttributeInternal(REMITTOSUPPLIERSITEID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute RelationshipId.
     * @return the RelationshipId
     */
    public BigDecimal getRelationshipId() {
        return (BigDecimal) getAttributeInternal(RELATIONSHIPID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute RelationshipId.
     * @param value value to set the  RelationshipId
     */
    public void setRelationshipId(BigDecimal value) {
        setAttributeInternal(RELATIONSHIPID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute RemitToSupplierNum.
     * @return the RemitToSupplierNum
     */
    public String getRemitToSupplierNum() {
        return (String) getAttributeInternal(REMITTOSUPPLIERNUM);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute RemitToSupplierNum.
     * @param value value to set the  RemitToSupplierNum
     */
    public void setRemitToSupplierNum(String value) {
        setAttributeInternal(REMITTOSUPPLIERNUM, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> SupplierNameLOV.
     */
    public RowSet getSupplierNameLOV() {
        return (RowSet)getAttributeInternal(SUPPLIERNAMELOV);
    }

    /**
     * Gets the view accessor <code>RowSet</code> SupplierNumberLOV.
     */
    public RowSet getSupplierNumberLOV() {
        return (RowSet)getAttributeInternal(SUPPLIERNUMBERLOV);
    }

    /**
     * Gets the view accessor <code>RowSet</code> InvoiceStatusLOV.
     */
    public RowSet getInvoiceStatusLOV() {
        return (RowSet)getAttributeInternal(INVOICESTATUSLOV);
    }
}
