package model.view;

import model.am.util.FndUserBean;

import oracle.adf.share.ADFContext;

import oracle.jbo.server.ViewObjectImpl;
import oracle.jbo.server.ViewRowSetImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jul 20 00:02:04 CEST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ConfigurationViewHeaderVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public ConfigurationViewHeaderVOImpl() {
    }

    /**
     * Returns the bind variable value for bind_user_id.
     * @return bind variable value for bind_user_id
     */
    public Integer getbind_user_id() {
        return (Integer)getNamedWhereClauseParam("bind_user_id");
    }

    /**
     * Sets <code>value</code> for bind variable bind_user_id.
     * @param value value to bind as bind_user_id
     */
    public void setbind_user_id(Integer value) {
        setNamedWhereClauseParam("bind_user_id", value);
    }

    /**@override Method to prepare RowSet for execution(Framework Internal Method) * @param viewRowSetImpl */
    public void prepareRowSetForQuery(ViewRowSetImpl viewRowSetImpl) {
        //Set Bind Variable's value
        FndUserBean fndUser =
            (FndUserBean)ADFContext.getCurrent().getSessionScope().get("fndUserBean");
        viewRowSetImpl.ensureVariableManager().setVariableValue("bind_user_id",
                                                                fndUser.getUserId());
        super.prepareRowSetForQuery(viewRowSetImpl);
    }

}
