package model.am.client;

import java.util.List;

import model.am.common.CommonAppModule;

import oracle.jbo.client.remote.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jun 22 15:22:12 CEST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CommonAppModuleClient extends ApplicationModuleImpl implements CommonAppModule {
    /**
     * This is the default constructor (do not remove).
     */
    public CommonAppModuleClient() {
    }

    public void checkAMConn() {
        Object _ret = this.riInvokeExportedMethod(this,"checkAMConn",null,null);
        return;
    }

    public List getViewObjectAttributes() {
        Object _ret =
            this.riInvokeExportedMethod(this,"getViewObjectAttributes",null,null);
        return (List)_ret;
    }
}
