package model.view.client;

import model.view.common.ApInvoiceSearchVVO;

import oracle.jbo.client.remote.ViewUsageImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jul 19 22:24:39 CEST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ApInvoiceSearchVVOClient extends ViewUsageImpl implements ApInvoiceSearchVVO {
    /**
     * This is the default constructor (do not remove).
     */
    public ApInvoiceSearchVVOClient() {
    }

    public void searchInvoice(String vendorName, Integer vendorNumber,
                              String currencyCode, String maturityStartDate,
                              String maturityEndDate, String invoiceStartDate,
                              String invoiceEndDate, Long invoiceNumber,
                              String invoiceType, Long invoiceFromAmount,
                              Long invoiceToAmount, String invoiceStatus) {
        Object _ret =
            getApplicationModuleProxy().riInvokeExportedMethod(this,"searchInvoice",new String [] {"java.lang.String","java.lang.Integer","java.lang.String","java.lang.String","java.lang.String","java.lang.String","java.lang.String","java.lang.Long","java.lang.String","java.lang.Long","java.lang.Long","java.lang.String"},new Object[] {vendorName, vendorNumber, currencyCode, maturityStartDate, maturityEndDate, invoiceStartDate, invoiceEndDate, invoiceNumber, invoiceType, invoiceFromAmount, invoiceToAmount, invoiceStatus});
        return;
    }
}
