package model.view.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jul 19 22:24:39 CEST 2016
// ---------------------------------------------------------------------
public interface ApInvoiceSearchVVO extends ViewObject {
    void searchInvoice(String vendorName, Integer vendorNumber,
                       String currencyCode, String maturityStartDate,
                       String maturityEndDate, String invoiceStartDate,
                       String invoiceEndDate, Long invoiceNumber,
                       String invoiceType, Long invoiceFromAmount,
                       Long invoiceToAmount, String invoiceStatus);
}
